In [9]:
!pip install ipython-sql

Requirement already satisfied: ipython-sql in /usr/local/lib/python3.12/dist-packages (0.5.0)
Requirement already satisfied: prettytable in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (3.18.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (7.34.0)
Requirement already satisfied: sqlalchemy>=2.0 in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (2.0.51)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=2.0->ipython-sql) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=2.0->ipython-sql) (4.16.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (75.2.0)
Collecting jedi>=0.16 (from ipython->ipython-sql)
  Downloading jedi-0.20.0-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.2.2)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.12/dist-packages (from prettytable->ipython-sql) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.7)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Downloading jedi-0.20.0-py2.py3-none-any.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 55.9 MB/s eta 0:00:00
Installing collected packages: jedi
Successfully installed jedi-0.20.0

In [10]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("northwind.db")

In [11]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

                    name
0             Categories
1        sqlite_sequence
2   CustomerCustomerDemo
3   CustomerDemographics
4              Customers
5              Employees
6    EmployeeTerritories
7          Order Details
8                 Orders
9               Products
10               Regions
11              Shippers
12             Suppliers
13           Territories

In [12]:
query = """
SELECT
Products.ProductName,
SUM([Order Details].Quantity) AS TotalSold

FROM Products

JOIN [Order Details]

ON Products.ProductID=[Order Details].ProductID

GROUP BY Products.ProductName

ORDER BY TotalSold DESC

LIMIT 10;
"""

top_products = pd.read_sql(query, conn)

top_products

                       ProductName  TotalSold
0        Louisiana Hot Spiced Okra     206213
1           Sir Rodney's Marmalade     205637
2       Teatime Chocolate Biscuits     205487
3                   Sirop d'érable     205005
4              Gumbär Gummibärchen     204761
5                    Outback Lager     204403
6                   Ravioli Angelo     204251
7             Raclette Courdavault     204137
8  Uncle Bob's Organic Dried Pears     203970
9                    Sasquatch Ale     203667

In [13]:
top_customers = pd.read_sql(query, conn)

In [14]:
top_products

                       ProductName  TotalSold
0        Louisiana Hot Spiced Okra     206213
1           Sir Rodney's Marmalade     205637
2       Teatime Chocolate Biscuits     205487
3                   Sirop d'érable     205005
4              Gumbär Gummibärchen     204761
5                    Outback Lager     204403
6                   Ravioli Angelo     204251
7             Raclette Courdavault     204137
8  Uncle Bob's Organic Dried Pears     203970
9                    Sasquatch Ale     203667

In [15]:
top_products.head()

                  ProductName  TotalSold
0   Louisiana Hot Spiced Okra     206213
1      Sir Rodney's Marmalade     205637
2  Teatime Chocolate Biscuits     205487
3              Sirop d'érable     205005
4         Gumbär Gummibärchen     204761

In [16]:
top_products.describe()

           TotalSold
count      10.000000
mean   204753.100000
std       820.692452
min    203667.000000
25%    204165.500000
50%    204582.000000
75%    205366.500000
max    206213.000000

In [17]:
query = """
SELECT
    Customers.CompanyName,

    SUM(
        [Order Details].UnitPrice *
        [Order Details].Quantity
    ) AS Revenue

FROM Customers

JOIN Orders
ON Customers.CustomerID = Orders.CustomerID

JOIN [Order Details]
ON Orders.OrderID = [Order Details].OrderID

GROUP BY Customers.CompanyName

ORDER BY Revenue DESC

LIMIT 10;
"""

top_customers = pd.read_sql(query, conn)

top_customers

                          CompanyName     Revenue
0                                  IT  9745371.29
1                       B's Beverages  6154115.34
2          Hungry Coyote Import Store  5698023.67
3                       Rancho grande  5559110.08
4                 Gourmet Lanchonetes  5552597.90
5  Ana Trujillo Emparedados y helados  5534356.65
6                  Ricardo Adocicados  5524990.91
7                   Folies gourmandes  5505502.85
8                   Let's Stop N Shop  5462611.57
9                   LILA-Supermercado  5439186.80

In [18]:
top_product = top_products.iloc[0]

print("Highest selling product:", top_product["ProductName"])
print("Quantity sold:", top_product["TotalSold"])

Highest selling product: Louisiana Hot Spiced Okra
Quantity sold: 206213

In [30]:
top_customers

                          CompanyName     Revenue
0                                  IT  9745371.29
1                       B's Beverages  6154115.34
2          Hungry Coyote Import Store  5698023.67
3                       Rancho grande  5559110.08
4                 Gourmet Lanchonetes  5552597.90
5  Ana Trujillo Emparedados y helados  5534356.65
6                  Ricardo Adocicados  5524990.91
7                   Folies gourmandes  5505502.85
8                   Let's Stop N Shop  5462611.57
9                   LILA-Supermercado  5439186.80

In [19]:
top_customers.head()

                  CompanyName     Revenue
0                          IT  9745371.29
1               B's Beverages  6154115.34
2  Hungry Coyote Import Store  5698023.67
3               Rancho grande  5559110.08
4         Gourmet Lanchonetes  5552597.90

In [20]:
top_customer = top_customers.iloc[0]

print("Highest revenue customer:", top_customer["CompanyName"])
print("Revenue:", top_customer["Revenue"])

Highest revenue customer: IT
Revenue: 9745371.289999997

In [38]:
top_customers["Revenue"]

0    9745371.29
1    6154115.34
2    5698023.67
3    5559110.08
4    5552597.90
5    5534356.65
6    5524990.91
7    5505502.85
8    5462611.57
9    5439186.80
Name: Revenue, dtype: float64

In [40]:
query = """
SELECT
    Products.ProductName,
    SUM([Order Details].UnitPrice * [Order Details].Quantity) AS Revenue
FROM Products
JOIN [Order Details]
ON Products.ProductID = [Order Details].ProductID
GROUP BY Products.ProductName
ORDER BY Revenue DESC;
"""

product_revenue = pd.read_sql(query, conn)

product_revenue.head()

               ProductName      Revenue
0            Côte de Blaye  53274482.70
1  Thüringer Rostbratwurst  24630836.96
2          Mishi Kobe Niku  19424638.00
3   Sir Rodney's Marmalade  16654879.80
4         Carnarvon Tigers  12607487.50

In [41]:
top10_revenue = product_revenue.head(10)["Revenue"].sum()
total_revenue = product_revenue["Revenue"].sum()
percentage = (top10_revenue / total_revenue) * 100
print(f"Top 10 products account for {percentage:.2f}% of total revenue")

Top 10 products account for 39.47% of total revenue

In [31]:
query = """
SELECT
    strftime('%Y-%m', Orders.OrderDate) AS Month,

    SUM(
        [Order Details].UnitPrice *
        [Order Details].Quantity
    ) AS MonthlySales

FROM Orders

JOIN [Order Details]
ON Orders.OrderID = [Order Details].OrderID

GROUP BY Month

ORDER BY Month;
"""

monthly_sales = pd.read_sql(query, conn)

monthly_sales

       Month  MonthlySales
0    2012-07    2066219.40
1    2012-08    3556875.79
2    2012-09    3440144.98
3    2012-10    3201529.96
4    2012-11    2980494.74
..       ...           ...
131  2023-06    3071787.73
132  2023-07    3350337.36
133  2023-08    3293158.67
134  2023-09    3544698.51
135  2023-10    2923364.35

[136 rows x 2 columns]

In [32]:
monthly_sales

       Month  MonthlySales
0    2012-07    2066219.40
1    2012-08    3556875.79
2    2012-09    3440144.98
3    2012-10    3201529.96
4    2012-11    2980494.74
..       ...           ...
131  2023-06    3071787.73
132  2023-07    3350337.36
133  2023-08    3293158.67
134  2023-09    3544698.51
135  2023-10    2923364.35

[136 rows x 2 columns]

In [28]:
monthly_sales.head()

     Month  MonthlySales
0  2012-07    2066219.40
1  2012-08    3556875.79
2  2012-09    3440144.98
3  2012-10    3201529.96
4  2012-11    2980494.74

In [29]:
best_month = monthly_sales.loc[
    monthly_sales["MonthlySales"].idxmax()
]

print("Highest sales month:", best_month["Month"])
print("Sales:", best_month["MonthlySales"])

Highest sales month: 2021-12
Sales: 4377795.399999986

In [33]:
query = """
SELECT
    Categories.CategoryName,

    SUM(
        [Order Details].UnitPrice *
        [Order Details].Quantity
    ) AS Revenue

FROM Categories

JOIN Products
ON Categories.CategoryID = Products.CategoryID

JOIN [Order Details]
ON Products.ProductID = [Order Details].ProductID

GROUP BY Categories.CategoryName

ORDER BY Revenue DESC;
"""

category_sales = pd.read_sql(query, conn)

category_sales

     CategoryName      Revenue
0       Beverages  92181842.95
1     Confections  66347544.94
2    Meat/Poultry  64896314.41
3  Dairy Products  58034940.00
4      Condiments  55802774.45
5         Seafood  49931965.52
6         Produce  32706403.90
7  Grains/Cereals  28573512.55

In [34]:
category_sales

     CategoryName      Revenue
0       Beverages  92181842.95
1     Confections  66347544.94
2    Meat/Poultry  64896314.41
3  Dairy Products  58034940.00
4      Condiments  55802774.45
5         Seafood  49931965.52
6         Produce  32706403.90
7  Grains/Cereals  28573512.55

In [35]:
best_category = category_sales.loc[
    category_sales["Revenue"].idxmax()
]

print("Best category:", best_category["CategoryName"])
print("Revenue:", best_category["Revenue"])

Best category: Beverages
Revenue: 92181842.95

In [36]:
query = """
SELECT

    Customers.CompanyName,

    COUNT(Orders.OrderID) AS TotalOrders

FROM Customers

JOIN Orders

ON Customers.CustomerID = Orders.CustomerID

GROUP BY Customers.CompanyName

ORDER BY TotalOrders DESC;
"""

purchase_frequency = pd.read_sql(query, conn)

purchase_frequency

                             CompanyName  TotalOrders
0                                     IT          335
1                          B's Beverages          210
2                     Ricardo Adocicados          203
3                      LILA-Supermercado          203
4                    Gourmet Lanchonetes          202
..                                   ...          ...
87                       Around the Horn          156
88                  La corne d'abondance          155
89        Furia Bacalhau e Frutos do Mar          155
90  FISSA Fabrica Inter. Salchichas S.A.          155
91                Océano Atlántico Ltda.          154

[92 rows x 2 columns]

In [37]:
frequent_customer = purchase_frequency.iloc[0]

print("Most frequent customer:", frequent_customer["CompanyName"])
print("Number of orders:", frequent_customer["TotalOrders"])

Most frequent customer: IT
Number of orders: 335